In [1]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
plt.rc('font', family='serif', size=16)

In [2]:
L = 1.0
nx = 51
dx = L / (nx-1)
x = np.linspace(0.0, L, nx)

alpha = 0.00122
q = 0.0

T0 = np.zeros(nx)
T0[0] = 100.0

In [26]:
def btcs(u0, nt, dt, dx, alpha, ligma, q=0.0):
    u = u0.copy()
    ligma = alpha*dt/dx**2
    A=lhs_operator(nx, ligma)
    for n in range(nt):
        b = rhs_vector(u, ligma, q*dx)
        u[1:-1] = np.linalg.solve(A, b)
        # Update boundary values
        u[0] = u0[0]
        u[-1] = u[-2] + q*dx
    return u

In [27]:
def lhs_operator(N, ligma):
    #Diagonal Coefficients
    D = np.diag((2 + 1/ligma) * np.ones(N))
    D[-1, -1] = 1 + 1 / ligma
    #Upper Diagonal
    U = np.diag(-1.0 * np.ones(N - 1), k=1)
    #Lower Diagonal
    L = np.diag(-1.0 * np.ones(N-1), k=-1)
    
    #Assemble A
    A = D + U + L
    return A
print(lhs_operator(51, 0.5))

[[ 4. -1.  0. ...  0.  0.  0.]
 [-1.  4. -1. ...  0.  0.  0.]
 [ 0. -1.  4. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  4. -1.  0.]
 [ 0.  0.  0. ... -1.  4. -1.]
 [ 0.  0.  0. ...  0. -1.  3.]]


In [28]:
def rhs_vector(T, ligma, qdx):
    b = T[1:-1] / ligma
    #Dirichlet
    b[0] += T[0]
    #Neumann
    b[-1] += qdx
    return b

In [29]:
nt = 1000
sigma = 0.5
dt = sigma * dx**2 / alpha

T = btcs(T0, nt, dt, dx, alpha, sigma)

plt.plot(x, T)
plt.xlim(0.0, L)
plt.ylim(0.0, 100.0)

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 49 is different from 51)